### ISSUE TITLE
No deny event is exposed

### ISSUE THREAD

**Issue by OptimusKrish** [michalstocki/FlashWavRecorder#59]
When user clicks on deny button in the permission popup there is no event exposed to handle. Is it possible to provide a work around for this? 
Example:  
```javascript
$('#status').text("Last recorder event: " + arguments[0]);
```
In this case `arguments[0]` is empty.

Screenshot of code base:
![image](https://cloud.githubusercontent.com/assets/7058950/9760538/a0230e96-5713-11e5-98ec-09afb5847bfa.png)

**Comment by michalstocki** [comment]
Thanks for the issue. I'll look at this during next update.

**Comment by OptimusKrish** [comment]
Is it possible to know the ETA for next update, as I need to update the same code in my application.

**Comment by OptimusKrish** [comment]
This is happening when user clicks on deny and checks on remembers option. As result we cannot able to catch the event and show the permission popup or any alert message to user.

**Comment by michalstocki** [comment]
Thanks for the reminder. What operating system and browser do you use? I tried to reproduce this problem on Chrome, Firefox and Safari on Mac, and the every time when I click "deny" button on the permission popup, the event called `microphone_not_connected` is fired.

For easier watching recorder events, I modified [demo page](http://michalstocki.github.io/FlashWavRecorder/html/) to make visible all events instead of the only last one.

**Comment by OptimusKrish** [comment]
Thanks @michalstocki . Now I can able to get the event and its behaviour. Mistake was from my side. Sorry for the in-convince caused and once again thanks for your timely help.
