### ISSUE TITLE
Playing external wav file

### ISSUE THREAD

**Issue by mohammedshoib** [michalstocki/FlashWavRecorder#67]
hi, is there a way to play external wav file? 

Problem:

1) I have recorded audio file from flash player i.e wav file and saved to server.
2) Then i reload the page, i will get the recorded wav file from the server, now i need to play that using your flash i.e because IE browser does not support playing wav file.

How can i achieve to play wav file? you can also refer me for other resource as well, it will be helpful for me.

Thanks.

**Comment by michalstocki** [comment]
It's rather not possible to use FlashWavRecorder as player for .wav files. That's because we haven't any logic for decoding wav files. FWR collects raw microphone samples and encode it to WAV file only for export. In playback we use raw samples (not exported .wav).

I suggest to use one of the existing libraries. There is an question on Stackoverflow on this topic: http://stackoverflow.com/questions/857037/flash-based-wav-player
