### ISSUE TITLE
[Help] How to get multiple recorders on a single page

### ISSUE THREAD

**Issue by absorbjava** [michalstocki/FlashWavRecorder#71]
how to integrate more than one recorder in the same page ?

**Comment by michalstocki** [comment]
You can set up multiple recorder controls using a single embedded swf object. Such configuration is demonstrated in the [advanced demo page](http://michalstocki.github.io/FlashWavRecorder/html/), uploading recordings via flash in this configuration is more complex and was not tested (I suggest to use XHR upload instead of flash).
